오류수정중
MissingReferenceException: The object of type 'RectTransform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.set_position (UnityEngine.Vector3 value) (at <f7237cf7abef49bfbb552d7eb076e422>:0)
HandManager+<MoveCard>d__18.MoveNext () (at Assets/Dev_Folder/SJ/Scripts/HandManager.cs:88)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <f7237cf7abef49bfbb552d7eb076e422>:0)